### ISSUE TITLE
API error:  TypeError: Cannot read properties of null (reading 'map')

### ISSUE THREAD

**Issue by pmobis** [qunash/chatgpt-advanced#102]
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.react%2F7.21.1:1          Failed to load resource: the server responded with a status of 429 ()
/backend-api/conversation/gen_title/f2a0271a-126a-4220-814e-2992bb0d73a8:1          Failed to load resource: the server responded with a status of 500 ()
_app-0d8cf08d7acf0ea7.js:7 FatalError: Something went wrong. If this issue persists please contact us through our help center at help.openai.com.
    at 264-2e813ac49ec5d2d2.js:1:1356
    at main-149b337e061b4d04.js:1:101106
    at Object.next (main-149b337e061b4d04.js:1:101211)
    at r (_app-0d8cf08d7acf0ea7.js:16:1497)
    at a (_app-0d8cf08d7acf0ea7.js:16:1694)
(anonymous) @ _app-0d8cf08d7acf0ea7.js:7
mainUI.js:2648 WebChatGPT error --> API error:  TypeError: Cannot read properties of null (reading 'map')
    at apiSearch (mainUI.js:2580:20)
    at async HTMLTextAreaElement.onSubmit (mainUI.js:2624:25)
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
chatGptInjection.js:58          GET https://chat.openai.com/api/auth/session 403
getToken @ chatGptInjection.js:58
getToken @ chatGptInjection.js:60
init @ chatGptInjection.js:60
Fi @ chatGptInjection.js:60
injectSender @ chatGptInjection.js:60
init @ chatGptInjection.js:60
wu @ chatGptInjection.js:60
(anonymous) @ chatGptInjection.js:60
(anonymous) @ chatGptInjection.js:60
chat:1 Uncaught (in promise) CLOUDFLARE

**Comment by qunash** [comment]
> The resource was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally. o33249.ingest.sentry.io/api/4504238875803648/envelope/?sentry_key=33f79e998f93410882ecec1e57143840&sentry_version=7&sentry_client=sentry.javascript.react%2F7.21.1:1 Failed to load resource: the server responded with a status of 429 () /backend-api/conversation/gen_title/f2a0271a-126a-4220-814e-2992bb0d73a8:1 Failed to load resource: the server responded with a status of 500 () _app-0d8cf08d7acf0ea7.js:7 FatalError: Something went wrong. If this issue persists please contact us through our help center at help.openai.com. at 264-2e813ac49ec5d2d2.js:1:1356 at main-149b337e061b4d04.js:1:101106 at Object.next (main-149b337e061b4d04.js:1:101211) at r (_app-0d8cf08d7acf0ea7.js:16:1497) at a (_app-0d8cf08d7acf0ea7.js:16:1694) (anonymous) @ _app-0d8cf08d7acf0ea7.js:7 mainUI.js:2648 WebChatGPT error --> API error: TypeError: Cannot read properties of null (reading 'map') at apiSearch (mainUI.js:2580:20) at async HTMLTextAreaElement.onSubmit (mainUI.js:2624:25) DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND chatGptInjection.js:58 GET https://chat.openai.com/api/auth/session 403 getToken @ chatGptInjection.js:58 getToken @ chatGptInjection.js:60 init @ chatGptInjection.js:60 Fi @ chatGptInjection.js:60 injectSender @ chatGptInjection.js:60 init @ chatGptInjection.js:60 wu @ chatGptInjection.js:60 (anonymous) @ chatGptInjection.js:60 (anonymous) @ chatGptInjection.js:60 chat:1 Uncaught (in promise) CLOUDFLARE

This does not look like an error from WebChatGPT extension.

**Comment by pmobis** [comment]
Yes was logged in. multiple browser refreshes later and a different query it worked again.

**Comment by qunash** [comment]
You most likely have some other chatgpt extension(s) that are interfering with WebChatGPT. Try disabling all other extensions and see if the problem goes away.
